'use strict';
/**
 * The full per-photo credit map both page generators read from: Wikimedia
 * Commons photos (data/image-credits.json, generated by fetch-images.js) plus
 * any you've added yourself (data/custom-photos.json, hand-maintained — see
 * docs/ADMIN.md). Both use the same shape per entry: local, author, licence,
 * licenceUrl, filePage. A custom entry simply wins if its key collides with a
 * Commons one, which shouldn't happen since custom keys are always prefixed
 * `custom:`.
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');

function readImages(file) {
  const p = path.join(ROOT, 'data', file);
  if (!fs.existsSync(p)) return {};
  return JSON.parse(fs.readFileSync(p, 'utf8')).images || {};
}

function loadImageCredits() {
  return { ...readImages('image-credits.json'), ...readImages('custom-photos.json') };
}

module.exports = { loadImageCredits };
